site_name: EUDI Wallet
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - European digital identity: index.md
  - Architecture and reference framework: arf.md
