# Deploy ARF as static content to GitHub Pages
name: Deploy ARF to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
           ref: 'v1.5.1'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mike
      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: git pull origin v1.5.1
      - run: mike deploy --push --update-aliases 1.5.1
      - run: mike set-default --push 1.5.1
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: latest
      - run: sudo apt update -y
      - run: sudo apt install -y texlive-full texlive-xetex
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: architecture-and-reference-framework
          path: build/pdf
